from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PROTOCOL_ROOT = ROOT / "protocol" / "python"
if __package__ in {None, ""}:
    for import_root in (ROOT, PROTOCOL_ROOT):
        if str(import_root) not in sys.path:
            sys.path.insert(0, str(import_root))

import scripts.collect_moto_g_validation_bundle as bundle  # noqa: E402
import scripts.guide_moto_g_validation as guide  # noqa: E402
import scripts.record_moto_g_smoke as smoke  # noqa: E402

JSON_SCHEMA_VERSION = "goffy.moto-g-validation-bundle-verification.v1"
MAX_JSON_BYTES = 1024 * 1024
MAX_ARTIFACT_BYTES = 1024 * 1024
MAX_TEXT_BYTES = 1024 * 1024
EXPECTED_ARTIFACTS = frozenset({"guide.json", "guide.txt", "smoke.json", "smoke.txt"})
EXPECTED_METADATA = {
    "manifest.json": "bundle manifest",
    bundle.BUNDLE_MARKER: "force-overwrite safety marker",
}
ALLOWED_BUNDLE_FILES = EXPECTED_ARTIFACTS | frozenset(EXPECTED_METADATA)


@dataclass(frozen=True)
class BundleCheck:
    check_id: str
    ok: bool
    detail: str
    remediation: str = ""


@dataclass(frozen=True)
class BundleVerification:
    bundle_dir: Path
    checks: tuple[BundleCheck, ...]
    bundle_name: str | None = None
    next_step_id: str | None = None
    physical_smoke_passed: bool = False

    @property
    def integrity_ok(self) -> bool:
        return all(check.ok for check in self.checks)

    @property
    def ok(self) -> bool:
        return self.integrity_ok and self.physical_smoke_passed

    @property
    def exit_code(self) -> int:
        if not self.integrity_ok:
            return 2
        return 0 if self.physical_smoke_passed else 1


def safe_relative_path(value: Any) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    posix = PurePosixPath(value)
    if posix.is_absolute() or ".." in posix.parts or "" in posix.parts:
        return None
    if "\\" in value:
        return None
    return posix.as_posix()


def contained_child(root: Path, relative_path: str) -> Path | None:
    candidate = root / relative_path
    try:
        candidate.resolve(strict=False).relative_to(root.resolve())
    except ValueError:
        return None
    return candidate


def read_json_object(path: Path) -> tuple[dict[str, Any] | None, BundleCheck]:
    if path.is_symlink():
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-not-symlink",
                ok=False,
                detail="JSON file is a symlink",
                remediation="Replace it with a regular file generated by GOFFY tooling.",
            ),
        )
    if not path.is_file():
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-exists",
                ok=False,
                detail="JSON file is missing",
                remediation="Regenerate the validation bundle.",
            ),
        )
    if path.stat().st_size > MAX_JSON_BYTES:
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-bounded-size",
                ok=False,
                detail=f"JSON file exceeds {MAX_JSON_BYTES} bytes",
                remediation="Inspect the bundle locally and regenerate it if unexpected.",
            ),
        )
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-valid-json",
                ok=False,
                detail=f"JSON parse failed: {exc.__class__.__name__}",
                remediation="Regenerate the validation bundle.",
            ),
        )
    if not isinstance(payload, dict):
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-json-object",
                ok=False,
                detail="JSON payload is not an object",
                remediation="Regenerate the validation bundle.",
            ),
        )
    return payload, BundleCheck(check_id=f"{path.name}-json-object", ok=True, detail="ready")


def read_text_artifact(path: Path) -> tuple[str | None, BundleCheck]:
    if path.is_symlink():
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-not-symlink",
                ok=False,
                detail="text artifact is a symlink",
                remediation="Replace it with a regular file generated by GOFFY tooling.",
            ),
        )
    if not path.is_file():
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-exists",
                ok=False,
                detail="text artifact is missing",
                remediation="Regenerate the validation bundle.",
            ),
        )
    if path.stat().st_size > MAX_TEXT_BYTES:
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-bounded-size",
                ok=False,
                detail=f"text artifact exceeds {MAX_TEXT_BYTES} bytes",
                remediation="Inspect the bundle locally and regenerate it if unexpected.",
            ),
        )
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        return (
            None,
            BundleCheck(
                check_id=f"{path.name}-readable",
                ok=False,
                detail=exc.__class__.__name__,
                remediation="Regenerate the validation bundle.",
            ),
        )
    return text, BundleCheck(check_id=f"{path.name}-readable", ok=True, detail="ready")


def manifest_schema_checks(
    *,
    bundle_dir: Path,
    manifest: dict[str, Any] | None,
) -> tuple[tuple[BundleCheck, ...], str | None, str | None, bool]:
    if manifest is None:
        return (), None, None, False

    bundle_name = manifest.get("bundleName")
    next_step_id = manifest.get("nextStepId")
    manifest_ok = manifest.get("ok")
    manifest_ok_is_bool = type(manifest_ok) is bool
    physical_smoke_passed = manifest_ok is True if manifest_ok_is_bool else False
    checks = [
        BundleCheck(
            check_id="manifest-schema-version",
            ok=manifest.get("schemaVersion") == bundle.JSON_SCHEMA_VERSION,
            detail=str(manifest.get("schemaVersion")),
            remediation="Use a supported GOFFY validation bundle schema.",
        ),
        BundleCheck(
            check_id="manifest-bundle-name",
            ok=bundle_name == bundle_dir.name,
            detail=str(bundle_name),
            remediation="Keep the bundle directory name aligned with manifest.bundleName.",
        ),
        BundleCheck(
            check_id="manifest-local-only",
            ok=manifest.get("localOnly") is True,
            detail=str(manifest.get("localOnly")),
            remediation="Regenerate the bundle with the local-only collector.",
        ),
        BundleCheck(
            check_id="manifest-phone-mutation",
            ok=manifest.get("phoneMutation") is False,
            detail=str(manifest.get("phoneMutation")),
            remediation="Reject bundles that claim phone mutation occurred.",
        ),
        BundleCheck(
            check_id="manifest-ok-shape",
            ok=manifest_ok_is_bool,
            detail=str(manifest_ok),
            remediation="Regenerate the bundle with a boolean manifest.ok value.",
        ),
        BundleCheck(
            check_id="manifest-next-step-shape",
            ok=next_step_id is None or isinstance(next_step_id, str),
            detail=str(next_step_id),
            remediation="Regenerate the validation bundle.",
        ),
    ]
    return (
        tuple(checks),
        bundle_name if isinstance(bundle_name, str) else None,
        next_step_id if isinstance(next_step_id, str) else None,
        physical_smoke_passed,
    )


def validate_artifacts(
    *,
    bundle_dir: Path,
    manifest: dict[str, Any] | None,
) -> tuple[BundleCheck, ...]:
    if manifest is None:
        return ()
    entries = manifest.get("artifactFiles")
    if not isinstance(entries, list):
        return (
            BundleCheck(
                check_id="artifact-list-shape",
                ok=False,
                detail="artifactFiles is not a list",
                remediation="Regenerate the validation bundle.",
            ),
        )

    checks: list[BundleCheck] = []
    seen: list[str] = []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{index}-shape",
                    ok=False,
                    detail="artifact entry is not an object",
                    remediation="Regenerate the validation bundle.",
                )
            )
            continue
        relative_path = safe_relative_path(entry.get("relativePath"))
        if relative_path is None:
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{index}-path",
                    ok=False,
                    detail="artifact relativePath is unsafe or invalid",
                    remediation="Reject this bundle and regenerate evidence.",
                )
            )
            continue
        if relative_path not in EXPECTED_ARTIFACTS:
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{relative_path}-expected",
                    ok=False,
                    detail="artifact is not part of the v1 bundle contract",
                    remediation="Reject this bundle and regenerate evidence.",
                )
            )
            continue
        seen.append(relative_path)
        artifact_path = contained_child(bundle_dir, relative_path)
        if artifact_path is None:
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{relative_path}-contained",
                    ok=False,
                    detail="artifact path resolves outside the bundle",
                    remediation="Reject this bundle and regenerate evidence.",
                )
            )
            continue
        size_bytes = entry.get("sizeBytes")
        expected_sha256 = entry.get("sha256")
        if artifact_path.is_symlink():
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{relative_path}-not-symlink",
                    ok=False,
                    detail="artifact is a symlink",
                    remediation="Reject this bundle and regenerate evidence.",
                )
            )
            continue
        if not artifact_path.is_file():
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{relative_path}-exists",
                    ok=False,
                    detail="artifact file is missing",
                    remediation="Regenerate the validation bundle.",
                )
            )
            continue
        actual_size = artifact_path.stat().st_size
        if actual_size > MAX_ARTIFACT_BYTES:
            checks.append(
                BundleCheck(
                    check_id=f"artifact-{relative_path}-bounded-size",
                    ok=False,
                    detail=f"artifact exceeds {MAX_ARTIFACT_BYTES} bytes",
                    remediation="Reject this bundle and inspect it locally before sharing.",
                )
            )
            continue
        actual_sha256 = bundle.sha256_file(artifact_path)
        valid_size = type(size_bytes) is int and size_bytes >= 0
        checks.extend(
            (
                BundleCheck(
                    check_id=f"artifact-{relative_path}-size",
                    ok=valid_size and size_bytes == actual_size,
                    detail=f"expected:{size_bytes}; actual:{actual_size}",
                    remediation="Reject this bundle and regenerate evidence.",
                ),
                BundleCheck(
                    check_id=f"artifact-{relative_path}-sha256",
                    ok=isinstance(expected_sha256, str) and expected_sha256 == actual_sha256,
                    detail=f"expected:{expected_sha256}; actual:{actual_sha256}",
                    remediation="Reject this bundle and regenerate evidence.",
                ),
            )
        )
    checks.append(
        BundleCheck(
            check_id="artifact-set",
            ok=set(seen) == EXPECTED_ARTIFACTS and len(seen) == len(set(seen)),
            detail=", ".join(sorted(seen)),
            remediation="Regenerate the validation bundle with the current collector.",
        )
    )
    return tuple(checks)


def validate_metadata(
    *,
    bundle_dir: Path,
    manifest: dict[str, Any] | None,
) -> tuple[BundleCheck, ...]:
    if manifest is None:
        return ()
    entries = manifest.get("metadataFiles")
    if not isinstance(entries, list):
        return (
            BundleCheck(
                check_id="metadata-list-shape",
                ok=False,
                detail="metadataFiles is not a list",
                remediation="Regenerate the validation bundle.",
            ),
        )
    seen: dict[str, str] = {}
    checks: list[BundleCheck] = []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            checks.append(
                BundleCheck(
                    check_id=f"metadata-{index}-shape",
                    ok=False,
                    detail="metadata entry is not an object",
                    remediation="Regenerate the validation bundle.",
                )
            )
            continue
        relative_path = safe_relative_path(entry.get("relativePath"))
        role = entry.get("role")
        if relative_path is None or not isinstance(role, str) or not role:
            checks.append(
                BundleCheck(
                    check_id=f"metadata-{index}-fields",
                    ok=False,
                    detail="metadata entry fields are invalid",
                    remediation="Regenerate the validation bundle.",
                )
            )
            continue
        seen[relative_path] = role
    checks.append(
        BundleCheck(
            check_id="metadata-set",
            ok=seen == EXPECTED_METADATA,
            detail=json.dumps(seen, sort_keys=True),
            remediation="Regenerate the validation bundle with the current collector.",
        )
    )
    marker = bundle_dir / bundle.BUNDLE_MARKER
    marker_ok = False
    marker_detail = "missing"
    if marker.is_file() and not marker.is_symlink():
        try:
            marker_text = marker.read_text(encoding="utf-8")
            marker_ok = marker_text == f"{bundle.JSON_SCHEMA_VERSION}\n"
            marker_detail = marker_text.strip()
        except (OSError, UnicodeDecodeError) as exc:
            marker_detail = exc.__class__.__name__
    checks.append(
        BundleCheck(
            check_id="metadata-marker",
            ok=marker_ok,
            detail=marker_detail,
            remediation="Regenerate the validation bundle.",
        )
    )
    return tuple(checks)


def validate_bundle_contents(bundle_dir: Path) -> tuple[BundleCheck, ...]:
    unexpected: list[str] = []
    try:
        for entry in bundle_dir.iterdir():
            if entry.name not in ALLOWED_BUNDLE_FILES:
                unexpected.append(entry.name)
    except OSError as exc:
        return (
            BundleCheck(
                check_id="bundle-contents-readable",
                ok=False,
                detail=exc.__class__.__name__,
                remediation="Inspect the bundle locally and regenerate evidence.",
            ),
        )
    return (
        BundleCheck(
            check_id="bundle-contents-only-expected-files",
            ok=not unexpected,
            detail=", ".join(sorted(unexpected)) or "expected-only",
            remediation="Remove unexpected files and regenerate the bundle.",
        ),
    )


def expected_guide_text(payload: dict[str, Any]) -> str | None:
    steps = payload.get("steps")
    if not isinstance(steps, list):
        return None
    lines = ["GOFFY Moto G physical validation guide"]
    lines.append(f"overall: {'passed' if payload.get('ok') is True else 'not-passed'}")
    lines.append(f"next-step: {payload.get('nextStepId') or 'none'}")
    lines.append("")
    lines.append("steps:")
    for step in steps:
        if not isinstance(step, dict):
            return None
        step_id = step.get("step_id")
        title = step.get("title")
        status = step.get("status")
        detail = step.get("detail")
        command = step.get("command", [])
        if not all(isinstance(value, str) for value in (step_id, title, status, detail)):
            return None
        if not isinstance(command, list) or not all(isinstance(part, str) for part in command):
            return None
        lines.append(f"[{status}] {step_id}: {title}")
        lines.append(f"       detail: {detail}")
        if command:
            lines.append(f"       command: {' '.join(command)}")
        if step.get("mutates_device") is True:
            lines.append("       mutates-device: true")
        if step.get("requires_confirmation") is True:
            lines.append("       requires-confirmation: true")
    lines.append("")
    if payload.get("ok") is True:
        lines.append("Physical Moto G validation evidence is complete.")
    else:
        lines.append("Follow the next non-DONE step; this guide does not control the phone.")
    return "\n".join(lines)


def expected_smoke_text(payload: dict[str, Any]) -> str | None:
    timestamp = payload.get("timestampUtc")
    apk = payload.get("apk")
    manual = payload.get("manual")
    blockers = payload.get("blockers")
    if not isinstance(timestamp, str) or not isinstance(apk, dict) or not isinstance(manual, dict):
        return None
    if not isinstance(blockers, list) or not all(isinstance(blocker, str) for blocker in blockers):
        return None
    lines = ["GOFFY Moto G physical smoke record"]
    lines.append(f"timestamp: {timestamp}")
    ready = payload.get("readyForManualSmoke") is True
    lines.append(f"readiness: {'ready' if ready else 'not-ready'}")
    if payload.get("manualFailed") is True:
        manual_status_summary = "failed"
    elif payload.get("manualPassed") is True:
        manual_status_summary = "passed"
    else:
        manual_status_summary = "not-passed"
    lines.append(f"manual: {manual_status_summary}")
    physical_smoke_passed = payload.get("physicalSmokePassed") is True
    lines.append(f"physical-smoke: {'passed' if physical_smoke_passed else 'not-passed'}")
    lines.append("")
    lines.append("apk:")
    relative_path = apk.get("relative_path")
    present = apk.get("present")
    if not isinstance(relative_path, str) or type(present) is not bool:
        return None
    lines.append(f"- path: {relative_path}")
    lines.append(f"- present: {str(present).lower()}")
    if present:
        lines.append(f"- size-bytes: {apk.get('size_bytes')}")
        lines.append(f"- sha256: {apk.get('sha256')}")
    lines.append("")
    lines.append("manual checklist:")
    for label in (
        "appLaunched",
        "commandSubmitted",
        "macStatusDisplayed",
        "timelineRecorded",
        "restartRestored",
    ):
        status = manual.get(label)
        if not isinstance(status, str):
            return None
        lines.append(f"- {label}: {status}")
    if blockers:
        lines.append("")
        lines.append("blockers:")
        for blocker in blockers:
            lines.append(f"- {blocker}")
    lines.append("")
    if physical_smoke_passed:
        lines.append("Physical Moto G smoke evidence is complete.")
    elif payload.get("manualFailed") is True:
        lines.append("The manual phone checklist has a failed item; fix it before rerunning.")
    elif not ready:
        lines.append("Resolve readiness blockers before treating the phone smoke test as valid.")
    else:
        lines.append("Run the manual phone checklist and record each result.")
    return "\n".join(lines)


def text_consistency_checks(
    *,
    bundle_dir: Path,
    guide_payload: dict[str, Any],
    smoke_payload: dict[str, Any],
) -> tuple[BundleCheck, ...]:
    guide_text, guide_text_check = read_text_artifact(bundle_dir / "guide.txt")
    smoke_text, smoke_text_check = read_text_artifact(bundle_dir / "smoke.txt")
    expected_guide = expected_guide_text(guide_payload)
    expected_smoke = expected_smoke_text(smoke_payload)
    guide_matches = expected_guide is not None and guide_text == expected_guide
    smoke_matches = expected_smoke is not None and smoke_text == expected_smoke
    return (
        guide_text_check,
        smoke_text_check,
        BundleCheck(
            check_id="guide-text-match",
            ok=guide_matches,
            detail="matched" if guide_matches else "mismatch",
            remediation="Regenerate the validation bundle.",
        ),
        BundleCheck(
            check_id="smoke-text-match",
            ok=smoke_matches,
            detail="matched" if smoke_matches else "mismatch",
            remediation="Regenerate the validation bundle.",
        ),
    )


def json_consistency_checks(
    *,
    bundle_dir: Path,
    manifest: dict[str, Any] | None,
) -> tuple[BundleCheck, ...]:
    if manifest is None:
        return ()
    guide_payload, guide_json_check = read_json_object(bundle_dir / "guide.json")
    smoke_payload, smoke_json_check = read_json_object(bundle_dir / "smoke.json")
    checks = [guide_json_check, smoke_json_check]
    if guide_payload is None or smoke_payload is None:
        return tuple(checks)
    manifest_ok = manifest.get("ok")
    guide_ok = guide_payload.get("ok")
    smoke_physical_passed = smoke_payload.get("physicalSmokePassed")
    checks.extend(
        (
            BundleCheck(
                check_id="guide-schema-version",
                ok=guide_payload.get("schemaVersion") == guide.JSON_SCHEMA_VERSION,
                detail=str(guide_payload.get("schemaVersion")),
                remediation="Regenerate the validation bundle with the current guide.",
            ),
            BundleCheck(
                check_id="smoke-schema-version",
                ok=smoke_payload.get("schemaVersion") == smoke.JSON_SCHEMA_VERSION,
                detail=str(smoke_payload.get("schemaVersion")),
                remediation="Regenerate the validation bundle with the current smoke recorder.",
            ),
            BundleCheck(
                check_id="manifest-guide-status-match",
                ok=type(manifest_ok) is bool
                and type(guide_ok) is bool
                and manifest_ok is guide_ok
                and manifest.get("nextStepId") == guide_payload.get("nextStepId"),
                detail=(
                    f"manifest ok/next:{manifest.get('ok')}/{manifest.get('nextStepId')}; "
                    f"guide ok/next:{guide_payload.get('ok')}/{guide_payload.get('nextStepId')}"
                ),
                remediation="Reject this bundle and regenerate evidence.",
            ),
            BundleCheck(
                check_id="guide-smoke-record-match",
                ok=guide_payload.get("smokeRecord") == smoke_payload,
                detail=(
                    "matched" if guide_payload.get("smokeRecord") == smoke_payload else "mismatch"
                ),
                remediation="Reject this bundle and regenerate evidence.",
            ),
            BundleCheck(
                check_id="smoke-physical-status-match",
                ok=type(manifest_ok) is bool
                and type(smoke_physical_passed) is bool
                and manifest_ok is smoke_physical_passed,
                detail=(
                    f"manifest:{manifest.get('ok')}; "
                    f"smoke:{smoke_payload.get('physicalSmokePassed')}"
                ),
                remediation="Reject this bundle and regenerate evidence.",
            ),
            *text_consistency_checks(
                bundle_dir=bundle_dir,
                guide_payload=guide_payload,
                smoke_payload=smoke_payload,
            ),
        )
    )
    return tuple(checks)


def verify_bundle(bundle_dir: Path) -> BundleVerification:
    resolved = bundle_dir.resolve()
    manifest_payload, manifest_json_check = read_json_object(resolved / "manifest.json")
    schema_checks, name, next_step_id, physical_smoke_passed = manifest_schema_checks(
        bundle_dir=resolved,
        manifest=manifest_payload,
    )
    checks = (
        manifest_json_check,
        *schema_checks,
        *validate_artifacts(bundle_dir=resolved, manifest=manifest_payload),
        *validate_metadata(bundle_dir=resolved, manifest=manifest_payload),
        *validate_bundle_contents(resolved),
        *json_consistency_checks(bundle_dir=resolved, manifest=manifest_payload),
    )
    return BundleVerification(
        bundle_dir=resolved,
        checks=checks,
        bundle_name=name,
        next_step_id=next_step_id,
        physical_smoke_passed=physical_smoke_passed,
    )


def existing_bundle_directory(value: str) -> Path:
    path = Path(value)
    if not path.is_dir():
        raise argparse.ArgumentTypeError("bundle directory must be an existing directory")
    return path


def render_json(verification: BundleVerification) -> str:
    payload: dict[str, Any] = {
        "schemaVersion": JSON_SCHEMA_VERSION,
        "ok": verification.ok,
        "integrityOk": verification.integrity_ok,
        "physicalSmokePassed": verification.physical_smoke_passed,
        "bundleName": verification.bundle_name,
        "nextStepId": verification.next_step_id,
        "checks": [{**asdict(check), "checkId": check.check_id} for check in verification.checks],
    }
    for check in payload["checks"]:
        check.pop("check_id", None)
    return json.dumps(payload, indent=2, sort_keys=True)


def render_text(verification: BundleVerification) -> str:
    lines = ["GOFFY Moto G validation bundle verification"]
    lines.append(f"bundle: {verification.bundle_name or verification.bundle_dir.name}")
    lines.append(f"integrity: {'passed' if verification.integrity_ok else 'failed'}")
    physical_status = "passed" if verification.physical_smoke_passed else "not-passed"
    lines.append(f"physical-smoke: {physical_status}")
    lines.append(f"overall: {'passed' if verification.ok else 'not-passed'}")
    lines.append(f"next-step: {verification.next_step_id or 'none'}")
    lines.append("")
    lines.append("checks:")
    for check in verification.checks:
        status = "OK" if check.ok else "FAIL"
        lines.append(f"[{status}] {check.check_id}: {check.detail}")
        if not check.ok and check.remediation:
            lines.append(f"       fix: {check.remediation}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("bundle_dir", type=existing_bundle_directory)
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    args = parser.parse_args(argv)

    verification = verify_bundle(args.bundle_dir)
    print(render_json(verification) if args.json else render_text(verification))
    return verification.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
