package dev.goffy.os.protocol

const val GIT_STATUS_TOOL = "git.status"
const val GOFFY_ROM_CHECKLIST_TOOL = "goffy.rom.checklist"
const val GOFFY_ROM_STATUS_TOOL = "goffy.rom.status"
const val MAC_APPS_LIST_TOOL = "mac.apps.list"
const val MAC_APPS_OPEN_TOOL = "mac.apps.open"
const val MAC_CLIPBOARD_READ_TOOL = "mac.clipboard.read"
const val MAC_SYSTEM_INFO_TOOL = "mac.system_info"
const val MAC_FILES_LARGEST_TOOL = "mac.files.largest"
const val MAC_FILES_LIST_TOOL = "mac.files.list"
const val MAC_PROCESSES_LIST_TOOL = "mac.processes.list"
const val PHONE_BATTERY_STATUS_TOOL = "phone.battery.status"
const val PHONE_DEVICE_INFO_TOOL = "phone.device.info"
const val PHONE_FLASHLIGHT_SET_TOOL = "phone.flashlight.set"
const val PHONE_MEMORY_FORGET_TOOL = "phone.memory.forget"
const val PHONE_MEMORY_FORGET_ALL_TOOL = "phone.memory.forget_all"
const val PHONE_MEMORY_LIST_TOOL = "phone.memory.list"
const val PHONE_MEMORY_REMEMBER_TOOL = "phone.memory.remember"
const val PHONE_MEMORY_UPDATE_TOOL = "phone.memory.update"
const val PHONE_NOTE_CREATE_TOOL = "phone.note.create"
const val PHONE_OCR_READ_TOOL = "phone.ocr.read"
const val PHONE_QR_READ_TOOL = "phone.qr.read"
const val PHONE_TIMER_CREATE_TOOL = "phone.timer.create"
